### ISSUE TITLE
Error after selecting which patches to send

### ISSUE THREAD

**Issue by glitzflitz** [stefanha/git-publish#101]
After selecting option `[s] Select patches to send (default: all)` and exiting GIT_EDITOR(in my case vim) after saving git publish gives this error
```
Traceback (most recent call last):
  File "/home/glitz/.local/bin/git-publish", line 914, in <module>
    sys.exit(main())
  File "/home/glitz/.local/bin/git-publish", line 871, in main
    selected_patches = inspect_menu(tmpdir, to, cc, patches, suppress_cc,
  File "/home/glitz/.local/bin/git-publish", line 468, in inspect_menu
    output = git_send_email(to_list, cc_list, patches, suppress_cc,
  File "/home/glitz/.local/bin/git-publish", line 247, in git_send_email
    return _git_with_stderr(*args[1:])[0]
  File "/home/glitz/.local/bin/git-publish", line 86, in _git_with_stderr
    print('git ' + ' '.join(args))
TypeError: sequence item 9: expected str instance, bytes found
```

**Comment by stefanha** [comment]
@glitzflitz Thanks for reporting this. I have pushed a fix. Hope it solves the issue!

**Comment by glitzflitz** [comment]
@stefanha Thanks  for the quick response. The issue is resolved now
