### ISSUE TITLE
on win32, the tmpfile are not created properly

### ISSUE THREAD

**Issue by lygstate** [stefanha/git-publish#109]
[p] Print final email headers (dry run)
[a] Send all
[q] Cancel (quit)
t
git var GIT_EDITOR
Traceback (most recent call last):
  File "C:\work\xemu\xemu-opengl\qemu\xemu\git-publish", line 933, in <module>
    sys.exit(main())
  File "C:\work\xemu\xemu-opengl\qemu\xemu\git-publish", line 890, in main
    selected_patches = inspect_menu(tmpdir, to, cc, patches, suppress_cc,
  File "C:\work\xemu\xemu-opengl\qemu\xemu\git-publish", line 512, in inspect_menu
    new_to_list = edit_email_list(to_list)
  File "C:\work\xemu\xemu-opengl\qemu\xemu\git-publish", line 459, in edit_email_list
    for line in open(tmpfile.name, "r").readlines():
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\lygstate\\AppData\\Local\\Temp\\tmpiwaxp3ta.txt'
按 Enter 键继续...:

**Comment by nirs** [comment]
@lygstate looks like this fixed by #100 and this issue can be closed.
