### ISSUE TITLE
Crash when choosing "[s] Select patches to send (default: all)"

### ISSUE THREAD

**Issue by libvirtmirror** [stefanha/git-publish#49]
I get a traceback when entering 's' in the menu:

```
$ git publish
Stopping so you can inspect the patch emails:
  cd /tmp/tmp06j47hq2

..snip...

[c] Edit Cc list in editor (save after edit)
[t] Edit To list in editor (save after edit)
[e] Edit patches in editor
[s] Select patches to send (default: all)
[p] Print final email headers (dry run)
[a] Send all
[q] Cancel (quit)
s
Traceback (most recent call last):
  File "/usr/bin/git-publish", line 814, in <module>
    sys.exit(main())
  File "/usr/bin/git-publish", line 780, in main
    options.override_cc)
  File "/usr/bin/git-publish", line 479, in inspect_menu
    listfile.write("\n".join(patches))
  File "/usr/lib64/python3.6/tempfile.py", line 483, in func_wrapper
    return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'

```

**Comment by libvirtmirror** [comment]
This was using  git-publish-1.4.3-1.fc28.noarch
