### ISSUE TITLE
git publish bails when commit short-log has special characteres

### ISSUE THREAD

**Issue by fidencio** [stefanha/git-publish#68]
Here's one example:
```
fidencio@laerte ~/src/upstream/osinfo-db $ git commit --allow-empty --signoff 
[wip/gitpublish_bug 6ec0de6] Fabiano Fidêncio
fidencio@laerte ~/src/upstream/osinfo-db $ git publish 
Stopping so you can inspect the patch emails:
  cd /tmp/tmp8zoabkwj

Traceback (most recent call last):
  File "/usr/bin/git-publish", line 416, in parse_header
    for h, c in header.decode_header(hdr):
  File "/usr/lib64/python3.7/email/header.py", line 80, in decode_header
    if not ecre.search(header):
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/git-publish", line 848, in <module>
    sys.exit(main())
  File "/usr/bin/git-publish", line 814, in main
    options.override_cc)
  File "/usr/bin/git-publish", line 452, in inspect_menu
    print(parse_header(m['subject']))
  File "/usr/bin/git-publish", line 422, in parse_header
    sys.stderr.write("Failed to parse email header: %s\n", hdr)
TypeError: write() takes exactly one argument (2 given)
```

**Comment by stefanha** [comment]
Please run "git format-patch -1 HEAD" and post the patch that is created.  When I try this on my system the character set decoding works correctly.  It's either related to environment variables or to the patch file itself.

**Comment by stefanha** [comment]
Please run "git format-patch -1 HEAD" and post the patch that is created.  When I try this on my system the character set decoding works correctly.  It's either related to environment variables or to the patch file itself.

By the way, I don't think this function will work properly with Python 3 since it uses the unicode() function, which is does exist :).  It needs to be rewritten but I'd still like to see your .patch file so I can test against it.

**Comment by stefanha** [comment]
Please try this branch:
https://github.com/stefanha/git-publish/commits/fix-parse_header

Hopefully it will solve the issue for you.

**Comment by fidencio** [comment]
> Please try this branch:
> https://github.com/stefanha/git-publish/commits/fix-parse_header
> 
> Hopefully it will solve the issue for you.

It breaks in a different way.
```
fidencio@laerte ~/src/upstream/osinfo-db $ /home/fidencio/src/upstream/git-publish/git-publish 
Stopping so you can inspect the patch emails:
  cd /tmp/tmppkvweu48

Traceback (most recent call last):
  File "/home/fidencio/src/upstream/git-publish/git-publish", line 847, in <module>
    sys.exit(main())
  File "/home/fidencio/src/upstream/git-publish/git-publish", line 810, in main
    options.override_cc)
  File "/home/fidencio/src/upstream/git-publish/git-publish", line 447, in inspect_menu
    print(parse_header(m['subject']))
  File "/home/fidencio/src/upstream/git-publish/git-publish", line 412, in parse_header
    for h, c in header.decode_header(hdr):
  File "/usr/lib64/python3.7/email/header.py", line 80, in decode_header
    if not ecre.search(header):
TypeError: expected string or bytes-like object
```
